######################################################################
# Automatically generated by qmake (2.01a) ? 11 16 19:26:40 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
HEADERS += glassmoon.h interfaces.h
SOURCES += glassmoon.cpp
HEADERS += mainwindow.h project.h 
SOURCES += mainwindow.cpp project.cpp

